# 部署VitePress文档到GitHub Pages的工作流
name: 部署VitePress文档

on:
  # 在推送到master分支时运行
  push:
    branches: ["master"]
    # 仅在docs目录或相关配置文件变化时触发
    paths:
      - 'docs/**'
      - '.vitepress/**'
      - 'package.json'
      - '.github/workflows/deploy-docs.yml'

  # 允许从Actions选项卡手动运行此工作流
  workflow_dispatch:

# 设置GITHUB_TOKEN的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 并发控制
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建和部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 确保获取所有历史记录和标签
          
      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # 使用npm全局安装pnpm - 这种方式更可靠
      - name: 安装pnpm
        run: npm install -g pnpm
        
      - name: 安装依赖
        run: pnpm install
        
      - name: 构建文档
        run: pnpm run docs:build
        
      - name: 上传构件
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传VitePress构建后的文档目录
          path: 'docs/.vitepress/dist'
          
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4